backend:
  name: github
  repo: pierreprezelin/portfolio-v3

media_folder: /static/media
public_folder: /media

media_libraries:
  default:
    max_file_size: 2048000
    slugify_filename: true
    config:
      transformations:
        raster_image:
          format: webp
          quality: 85
          width: 944
          height: 944
        svg:
          optimize: true

collections:
  - name: posts
    label: Posts
    folder: /src/content/posts
    path: '{{slug}}/index'
    media_folder: 'images'
    public_folder: 'images'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Cover Image, name: cover, widget: image }
      - { label: Body, name: body, widget: markdown }