backend:
  name: github
  repo: pierreprezelin/portfolio-v3

media_folder: /static/uploads
public_folder: /uploads

media_libraries:
  default:
    max_file_size: 2048000
    slugify_filename: true
    config:
      transformations:
        raster_image:
          format: webp
          quality: 100
          width: 944
          height: 944
        svg:
          optimize: true

collections:
  - name: posts
    label: Posts
    folder: /src/content/posts
    media_folder: '{{media_folder}}/blog'
    public_folder: '{{public_folder}}/blog'
    extension: "svx"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Date, name: date, widget: datetime, date_format: "DD/MM/YYYY", time_format: "HH:mm", format: "lll", picker_utc: true, default: '{{now}}' }
      - { label: Tags, name: tags, widget: list, required: false}
      - { label: Published, name: published, widget: boolean}
      - { label: Cover Image, name: cover, widget: image, required: false }
      - { label: Caption, name: caption, widget: string, required: false }
      - { label: Body, name: body, widget: markdown, required: false }